### ISSUE TITLE
Precompiled libs hosting is down

### ISSUE THREAD

**Issue by Aionsphere** [Lybr4/scummvm#2]
Precompiled libs : scummvm_vs_uwp_libs.zip is not accessible from the website specified (site looks down) in the Installation HOW TO page, unable to locate file anywhere else.

(link : http://www.mkort.de/scummvm_vs_uwp_libs.zip)

**Comment by Lybr4** [comment]
Thanks for the notice. The link should be fixed.

**Comment by Aionsphere** [comment]
Awesome, thanks!

FYI. https://twitter.com/MicrosoftTE/status/735275348082987008
